app:
  name: testiranje
  description: ${app.name} is a Spring Boot application
logging:
  path: /var/log
  file: testiranje-prod.log
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR
server:
  port: 8080
  sessionTimeout: 1800
security:
  user:
    password: test
spring:
  datasource:
    url: jdbc:mysql://localhost/testiranje
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev