app:
  name: testiranje
  description: ${app.name} is a Spring Boot application
logging:
  path: /var/log
  file: testiranje-dev.log
  level:
    org:
      springframework.web: DEBUG
      hibernate: DEBUG